<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Sphere10.Framework.Web.AspNetCore.Blazor\Sphere10.Framework.Web.AspNetCore.Blazor.csproj" />
    <ProjectReference Include="..\..\utils\Sphere10.Framework.Utils.BlazorTester\Sphere10.Framework.Utils.BlazorTester.csproj" />
  </ItemGroup>
</Project>
