<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Library</OutputType>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Properties\**" />
		<EmbeddedResource Remove="Properties\**" />
		<None Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Linq.Async" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Sphere10.Framework.Application\Sphere10.Framework.Application.csproj" />
		<ProjectReference Include="..\..\src\Sphere10.Framework.Communications\Sphere10.Framework.Communications.csproj" />
		<ProjectReference Include="..\..\src\Sphere10.Framework.NUnit\Sphere10.Framework.NUnit.csproj" />
		<ProjectReference Include="..\..\src\Sphere10.Framework.Generators\Sphere10.Framework.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../../pack.ps1" Link="Packaging/pack.ps1" CopyToOutputDirectory="PreserveNewest" />
		<None Include="../../publish.ps1" Link="Packaging/publish.ps1" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
