<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Library</OutputType>
	</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Sphere10.Framework.CryptoEx\Sphere10.Framework.CryptoEx.csproj" />
      <ProjectReference Include="..\..\src\Sphere10.Framework.NUnit\Sphere10.Framework.NUnit.csproj" />
      <ProjectReference Include="..\..\src\Sphere10.Framework\Sphere10.Framework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Resource.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resource.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resource.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\pascalCoinEciesCompatibilityVectors.json" />
		<EmbeddedResource Include="Resources\pascalCoinEciesEncryptionVectors.json" />
		<EmbeddedResource Include="Resources\pascalCoinEciesOversizedVectors.json" />
	</ItemGroup>

	<!-- In current version of BouncyCastle.Cryptography there is a problem with finding interfaces implementations. 
	     See here https://github.com/bcgit/bc-csharp/issues/447 for more details. -->

</Project>
