<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Sphere10.Framework.NUnit\Sphere10.Framework.NUnit.csproj" />
		<ProjectReference Include="..\..\src\Sphere10.Framework.Runtime\Sphere10.Framework.Runtime.csproj" />
		<ProjectReference Include="..\..\src\Sphere10.Framework\Sphere10.Framework.csproj" />
	</ItemGroup>

</Project>
