<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Sphere10.Framework.Web.AspNetCore.MVC\Sphere10.Framework.Web.AspNetCore.MVC.csproj" />
	</ItemGroup>
</Project>
