<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>net10.0</TargetFramework>
<OutputType>Library</OutputType>
</PropertyGroup>

<ItemGroup>
<PackageReference Include="NUnit" />
<PackageReference Include="NUnit3TestAdapter" />
<PackageReference Include="Microsoft.NET.Test.Sdk" />
</ItemGroup>

<ItemGroup>
<ProjectReference Include="..\..\src\Sphere10.Framework.Consensus\Sphere10.Framework.Consensus.csproj" />
<ProjectReference Include="..\..\src\Sphere10.Framework\Sphere10.Framework.csproj" />
</ItemGroup>
</Project>
