<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WorkflowCore.Persistence.EntityFramework" />
    <PackageReference Include="WorkflowCore.Persistence.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sphere10.Framework.Application\Sphere10.Framework.Application.csproj" />
    <ProjectReference Include="..\..\src\Sphere10.Framework.Windows.Forms\Sphere10.Framework.Windows.Forms.csproj" />
    <ProjectReference Include="..\..\src\Sphere10.Framework.Windows\Sphere10.Framework.Windows.csproj" />
    <ProjectReference Include="..\..\src\Sphere10.Framework\Sphere10.Framework.csproj" />
  </ItemGroup>

</Project>
